version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 167906152460.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - docker build -t cicd-nodejs-demo:latest .
      - docker tag cicd-nodejs-demo:latest 167906152460.dkr.ecr.us-west-2.amazonaws.com/cicd-nodejs-demo:latest
  post_build:
    commands:
      - docker push 167906152460.dkr.ecr.us-west-2.amazonaws.com/cicd-nodejs-demo:latest
      - printf '[{"name":"helloworld","imageUri":"%s"}]' 167906152460.dkr.ecr.us-west-2.amazonaws.com/cicd-nodejs-demo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
